### ISSUE TITLE
Mobile friendly updates to home page. 

### ISSUE THREAD

**Issue by Rickmusic** [Rickmusic/ScratchGames#21]
I believe we were moving the chat and online players boxes around to deal with this.

**Comment by oscarvelez** [comment]
something is happening with the collapse nav bar (where it shows: profile, leaderboards join code), it disappears when it goes to mobile size.
Having trouble with getting spaces between the divs despite putting a margin. 
Other than that, items stack on top of each other when screen size is smaller for tablet & mobile

**Comment by oscarvelez** [comment]
So I figured the navbar collapses entirely on mobile size but it's not like you can see a drop down menu available

**Comment by oscarvelez** [comment]
fixed collapse problem

**Comment by oscarvelez** [comment]
I think we can close this now
