### ISSUE TITLE
It's Slow

### ISSUE THREAD

**Issue by AylaJK** [Rickmusic/ScratchGames#31]
When sending messages through the socket to the server, and then back through the socket to the client seems slow. I have gone through and found that in my last commit ( c6ae6332769eb61a3043460ba2bca924c74adb0c ) the obvious `socket.on` functions, and client form on submit were not the source of the slowness.

I did quickly try disabling sessions (as they make DB queries per client request, including via websocket), but I did not see any performance improvement.

Some time will need to be spent combing through to determine the source of the slowness. When we get around to adding in the rest of the app's communication on sockets we will want it to be fast.

**Comment by Rickmusic** [comment]
This is strange indeed. I'll have to look though and see if I can find the source. What I had running on my machine before the changes seemed quick and there were few delays. Wondering if it's a machine or browser bug. Something that changed with the receiving of the form submit perhaps. I am unsure at this point and will try to look into it but even I doubt it's anything I've mentioned here.

**Comment by AylaJK** [comment]
So it's a new day (meaning my computer's gone through a full shutdown), and I updated to the newest npm (`npm install -g npm`), deleted `node_modules` and reinstalled them (`npm install`). Some combination therein fixed the slowness that I was experiencing, but as I only tested after doing all of the above (instead of between like I should have), I don't know exactly what was the culprit.
